// <auto-generated />
using System;
using MFR_MVC_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MFR_MVC_.Migrations
{
    [DbContext(typeof(MFRContext))]
    [Migration("20211027131750_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardChairName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedRotationYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("GlobalGroupAuditor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAltContactAlumni")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClientSalesforce")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContactAlumni")
                        .HasColumnType("bit");

                    b.Property<bool>("IsListedOnGhanaAlternativeMarket")
                        .HasColumnType("bit");

                    b.Property<bool>("IsListedOnStockExchange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecRegistrant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCompanyCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredecessorAuditor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RotationLawId")
                        .HasColumnType("int");

                    b.Property<int?>("SubIndustryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("RotationLawId");

                    b.HasIndex("SubIndustryId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industry");
                });

            modelBuilder.Entity("RotationLaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoolingPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RotationPeriod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RotationLaw");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.HasOne("Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.HasOne("RotationLaw", "RotationLaw")
                        .WithMany()
                        .HasForeignKey("RotationLawId");

                    b.HasOne("Industry", "SubIndustry")
                        .WithMany()
                        .HasForeignKey("SubIndustryId");

                    b.Navigation("Industry");

                    b.Navigation("RotationLaw");

                    b.Navigation("SubIndustry");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.HasOne("Client", null)
                        .WithMany("Services")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
